services:
  postgres-dev:
    container_name: postgres-dev-${INSTANCE_SUFFIX}
    image: postgres:${POSTGRES_VERSION}
    command:
      - "postgres"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_INIT_SCRIPTS_DIR}:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - db-network
  pgadmin:
    profiles: ["tools"]
    container_name: pgadmin_container-${INSTANCE_SUFFIX}
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - db-network
  postgres_exporter:
    profiles: ["monitoring"]
    container_name: exporter_container-${INSTANCE_SUFFIX}
    image: prometheuscommunity/postgres-exporter:${POSTGRES_EXPORTER_VERSION}
    environment:
      DATA_SOURCE_URI: "postgres-dev:5432/${POSTGRES_DB}?sslmode=disable"
      DATA_SOURCE_USER: ${POSTGRES_USER}
      DATA_SOURCE_PASS: ${POSTGRES_PASSWORD}
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
    volumes:
      - ./queries.yaml:/etc/postgres_exporter/queries.yaml:ro
    ports:
      - "9187:9187"
    restart: unless-stopped
    deploy:
      resources:
        limits:
         cpus: '0.2'
         memory: 500M
    networks:
      - db-network
  prometheus:
    profiles: ["monitoring"]
    image: prom/prometheus:${PROMETHEUS_VERSION}
    container_name: prometheus-${INSTANCE_SUFFIX}
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    ports:
      - "${PROMETHEUS_PORT}:9090"
    restart: unless-stopped
    networks:
      - db-network
  grafana:
    profiles: ["monitoring"]
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana-${INSTANCE_SUFFIX}
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - db-network
volumes:
  pg_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${POSTGRES_DATA_DIR}
  pgadmin_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PGADMIN_DATA_DIR}
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PROMETHEUS_DATA_DIR}
  grafana_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GRAFANA_DATA_DIR}
networks:
  db-network:
    driver: bridge